version: '3'

services:

  some-chamaeleon-api:
    depends_on:
      - some-chamaeleon-db
    image: chamaeleon-api
    ports:
      - 10000:80
    environment:
      WORDPRESS_DB_HOST: some-chamaeleon-db:3306
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  some-chamaeleon-db:
    image: chamaeleon-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}